### ISSUE TITLE
boxart repo

### ISSUE THREAD

**Issue by mzgoddard** [boxart/boxart-boiler#46]
Move RWD boiler to boxart/box-art boiler. Fix waffle, update blog post links

**Comment by boazsender** [comment]
What is this task?

**Comment by labond** [comment]
Make the base boxart repo and put stuff in it. Follow layout that Wilto designed. Pull things  out of the boilerplate so people can use them as standalones.

**Comment by labond** [comment]
Need to do this before we publish any blog posts

**Comment by mzgoddard** [comment]
Want to get travis testing in as the last thing to call this done.
