### ISSUE TITLE
Blog Post (short): Introduce BoxArt

### ISSUE THREAD

**Issue by labond** [boxart/boxart-boiler#57]
Follow on #51 to introduce BoxArt. Call out how it aligns with Bocoup philosophy. Follow template for introducing Grunt, Johnny-5, JQuery.

**Comment by labond** [comment]
Z will take a stab and maybe have Stine or someone else ghostwrite if needed

**Comment by mzgoddard** [comment]
https://bocoup.com/?p=3744&preview=true

https://docs.google.com/a/bocoup.com/document/d/1B7kncajatad8GglDr4nHZIJNSVLuuzpEcIb-Aqn1Sa0/edit?usp=sharing
