### ISSUE TITLE
boxart repo / batch

### ISSUE THREAD

**Issue by mzgoddard** [boxart/boxart-boiler#63]
Bring Batch over from boilerplate.

Batch is like a map over an array, but only gives the member data to the handler instead of member data, index, and the whole array. Batch assumes that a member's visualization changes when the member changes. Its position in the array and the array itself do not affect how it renders.

**Comment by kadamwhite** [comment]
Initial TODO: Open a PR on boxart/boxart with the code from the Batch components within Boxart-Boiler. @mzgoddard will review and we will pair to take that PR from initial migration to polished feature we can use on its own.
