### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by MattSurabian** [boxart/boxart-boiler#67]
The CI services are having a hard time with the repo move. Gotta totally reset them.

**Comment by labond** [comment]
Is this done? It looks finished.

**Comment by MattSurabian** [comment]
Not yet, the build tags still show "failing" because we've reached the limit for our browserstack account and likely need to get approval from folks to upgrade that plan. @mzgoddard and I did figured out why this was happening but haven't followed up on it with the right parties yet.

**Comment by boazsender** [comment]
Closing as a dup of #69
