### ISSUE TITLE
Sprite Animation

### ISSUE THREAD

**Issue by MattSurabian** [boxart/boxart-boiler#7]
Provide some kind of solution for spritesheet based animations in react components.

**Comment by labond** [comment]
make a branch that is a performance test for this to verify what limitations this method will have. How many concurrent animations can we have on which devices, how big can the animations be, what frame rates can they sustain?

**Comment by labond** [comment]
implementation should expect output from #38

**Comment by labond** [comment]
Don't forget to do documentation so people can use this.

**Comment by labond** [comment]
Closing this as it is absorbed into #72 and #86
